_target_: topobench.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "DiscreteConfigurationComplexLifting"
k: 2
feature_aggregation: "sum"
feature_lifting: ProjectionSum

# Required for all liftings to make the pipeline executable 
complex_dim: 3
preserve_edge_attr: False
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}
