_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 300
#accumulate_grad_batches: 1 #${dataset.parameters.batch_size}

accelerator: gpu
devices: [0]

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 5

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# inference mode: Whether to use :func:`torch.inference_mode` or :func:`torch.no_grad`
# during evaluation (``validate``/``test``/``predict``).
inference_mode: False
