global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Flink JobManager metrics
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']
    metrics_path: /
    scrape_interval: 5s

  # Flink TaskManager metrics  
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager-1:9249']
    metrics_path: /
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TDA Backend API metrics (if available)
  - job_name: 'tda-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
