transform_type: 'lifting'
transform_name: "HypergraphKernelLifting"
kernel_graph: heat
kernel_feat: identity
t: 1
feature_lifting: ProjectionSum
# Required for all liftings to make the pipeline executable 
preserve_edge_attr: False
complex_dim: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}