transform_type: 'lifting'
transform_name: "HypergraphKNNLifting"
k_value: 3
loop: True
feature_lifting: ProjectionSum
# Required for all liftings to make the pipeline executable 
preserve_edge_attr: False
complex_dim: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}