transform_type: "lifting"
transform_name: "MapperLifting"
filter_attr: "laplacian"
resolution: 10
gain: 0.3
filter_func:
# Required for all liftings to make the pipeline executable 
preserve_edge_attr: False
complex_dim: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}