transform_type: 'lifting'
transform_name: "ModularityMaximizationLifting"
num_communities: 2
k_neighbors: 3
feature_lifting: ProjectionSum
# Required for all liftings to make the pipeline executable 
preserve_edge_attr: False
complex_dim: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}