_target_: topobench.transforms.data_transform.DataTransform
transform_type: "lifting"
transform_name: "SimplicialLineLifting"
feature_lifting: ProjectionSum
# Required for all liftings to make the pipeline executable 
complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,3}
preserve_edge_attr: False
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}
