_target_: topobench.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "NeighborhoodComplexLifting"
signed: True
feature_lifting: ProjectionSum #ElementwiseMean
# Required for all liftings to make the pipeline executable 
complex_dim: 3
preserve_edge_attr: False
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}
