_target_: topobench.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialVietorisRipsLifting"
complex_dim: 3
signed: True
distance_threshold: 2.0
feature_lifting: ProjectionSum
preserve_edge_attr: False # This lifting do not explicitly preserves the graph structure, hence it is necessary to set preserve_edge_attr to False or modify the lifting source code.