# Dataset loader config
loader:
  _target_: topobench.data.loaders.GeometricShapesDatasetLoader
  parameters: 
    data_domain: pointcloud
    data_type: geometric_shapes
    data_name: geometric_shapes
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 3
  num_classes: 40
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random
  train_prop: 0.5

# Dataloader parameters
dataloader_params:
  batch_size: 10 # We have an issue with allowing multiple graphs in a batch due to sparse incidences
  num_workers: 0
  pin_memory: False

