loader:
  _target_: topobench.data.loaders.MantraSimplicialDatasetLoader
  parameters: 
    data_domain: simplicial
    data_type: topological 
    data_name: MANTRA
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    manifold_dim: 3
    version: "v0.0.5"
    load_as_graph: False
    task_variable: "betti_numbers" # Options: ['name', 'genus', 'orientable'] To use 'torsion_coefficients', 'betti_numbers' fix multilabel multiclass issue
    model_domain: ${model.model_domain}

# Data definition
parameters:
  # In the case of higher-order datasets we have multiple feature dimentions 
  num_features: [1,1,1]
  #num_classes: 2 # Num classes depents on the task_variable

  # Dataset parameters
  # task: classification     # TODO: adapt pipeline to support multilabel classification
  # loss_type: cross_entropy # TODO: adapt pipeline to support multilabel classification
  # monitor_metric: accuracy # TODO: adapt pipeline to support multilabel classification
  task_level: graph 
  data_seed: 0

#splits
split_params:
  learning_setting: inductive 
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 5
  num_workers: 0
  pin_memory: False
  persistent_workers: False