_target_: topobench.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "CombinatorialRingCloseAtomsLifting"
max_cell_length: null
preserve_edge_attr: True
feature_lifting: ProjectionSum

threshold_distance: 1.5